### ISSUE TITLE
Tried to install but does not work

### ISSUE THREAD

**Issue by WCMC-vblanque** [ChemicalLuck/qr-generator#1]
I tried to install with the command **pip install qrcode-logo-generator**  but it does not work.

It seems that the project is not already developed... you might say it in the README.

**Comment by ChemicalLuck** [comment]
I had not setup the workflow for PyPI publishing.

I have updated the readme and published the package.

`pip install qr-generator` will now work.

**Comment by WCMC-vblanque** [comment]
Thanks.
